

environment:
  passphrase:
    secure: En1qcj1/l2B3Nov+vOHlfRrFZk00bg1HPRouD64Gzfw=
  matrix:
    - PYTHON: "C:\\Python35\\python.exe"

install:
    - choco install swig
    - ps: iex ((New-Object Net.WebClient).DownloadString('https://raw.githubusercontent.com/appveyor/secure-file/master/install.ps1'))
    - appveyor-tools\secure-file -decrypt .coveralls.yml.enc -secret %passphrase%
    - "%PYTHON% -m pip install wheel tox cibuildwheel==0.10.1"


before_build:
    - before_build.bat %APPVEYOR_BUILD_FOLDER%

build_script:
    - "%PYTHON% cibuildwheel --output-dir wheelhouse"

#test_script:
#    - "%PYTHON%\\python.exe -m tox -v"

artifacts:
    - path: "wheelhouse\\*.whl"
      name: Wheels

cache:
  - C:\ProgramData\chocolatey\bin -> appveyor.yml
  - C:\ProgramData\chocolatey\lib -> appveyor.yml
  - C:\projects\swmm-python\.tox -> tox.ini
