

environment:
  passphrase:
    secure: En1qcj1/l2B3Nov+vOHlfRrFZk00bg1HPRouD64Gzfw=
  CIBW_SKIP: cp27-* cp34-* cp35-* *-win32
  CIBW_BUILD_VERBOSITY: 3
  CIBW_BEFORE_BUILD: pip install six
  CIBW_TEST_COMMAND: {project}\\tests
  CIBW_TEST_REQUIRES: pytest

  matrix:
    - PYTHON: "C:\\Python36"

install:
    - choco install swig
    - ps: iex ((New-Object Net.WebClient).DownloadString('https://raw.githubusercontent.com/appveyor/secure-file/master/install.ps1'))
    - appveyor-tools\secure-file -decrypt .coveralls.yml.enc -secret %passphrase%
    - "%PYTHON%\\python.exe --version"
    - "%PYTHON%\\python.exe -m pip install wheel cibuildwheel==0.10.1"


before_build:
    - before_build.bat %APPVEYOR_BUILD_FOLDER%

build_script:
    - "%PYTHON%\\python.exe -m cibuildwheel --output-dir wheelhouse"
    - "%PYTHON%\\python.exe -m cibuildwheel --output-dir wheelhouse .\\swmm_python\\output"
    - "%PYTHON%\\python.exe -m cibuildwheel --output-dir wheelhouse .\\swmm_python\\toolkit"

#test_script:
#    - "%PYTHON%\\python.exe -m tox -v"

artifacts:
    - path: "wheelhouse\\*.whl"
      name: Wheels

cache:
  - C:\ProgramData\chocolatey\bin -> appveyor.yml
  - C:\ProgramData\chocolatey\lib -> appveyor.yml
  - C:\projects\swmm-python\.tox -> tox.ini
