name: Build Wheels

on: [push, pull_request]

env:
  DOCKER_IMAGE: dockcross/manylinux2014-x64


jobs:
  build_linux_wheels:
    name: Build wheels on linux
    runs-on: ubuntu-18.04
    
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
        with:
          submodules: true

      - name: Install
        run: |
          docker pull $DOCKER_IMAGE
          docker run --rm $DOCKER_IMAGE > ./dockcross
          chmod +x ./dockcross

      - name: Script
        run: ./dockcross swmm-toolkit/tools/build-wheels.sh
      
      - uses: actions/upload-artifact@v2
        with:
          path: ./dist/swmm_toolkit*.whl



jobs:
  build_win-mac_wheels:
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [windows-2016, macos-10.15]
        py: [3.6, 3.7, 3.8, 3.9]

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
        with:
          submodules: true

      - name: Install Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.py }}

      - name: Install build requirements
        if: ${{ contains(matrix.os, 'windows') }}
        run: choco install swig

      - if: ${{ contains(matrix.os, 'macos') }}
        run: brew install libomp swig

      - name: Build wheel
        working-directory: ./swmm-toolkit
        run: |
          pip install setuptools wheel scikit-build cmake
          python setup.py bdist_wheel

      - name: Test wheel
        run: |
          pip install pytest numpy
          pip install --no-index --find-links=./dist swmm_toolkit
          pytest

      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          path: ./dist/swmm_toolkit*.whl
