name: Build

on: [push, pull_request]

env:
    CIBW_SKIP: "cp27-* cp34-* cp35-* cp36-* *-win32 *_i686 *_ppc64le *_s390x"
    CIBW_BEFORE_ALL: pip install six scikit-build cmake
    CIBW_BEFORE_ALL_LINUX: $CIBW_BEFORE_ALL && yum install -y swig
    CIBW_BEFORE_ALL_MACOS: $CIBW_BEFORE_ALL && brew install swig
    CIBW_BEFORE_ALL_WINDOWS: $CIBW_BEFORE_ALL && choco install swig
    CIBW_TEST_COMMAND: pytest {project}\\tests
    CIBW_TEST_REQUIRES: pytest numpy
    CIBW_MANYLINUX_X86_64_IMAGE: manylinux2014
    CIBW_MANYLINUX_AARCH64_IMAGE: manylinux2014
    CIBW_ENVIRONMENT: "PYTHON_INCLUDE_DIR=$(python -c "from distutils.sysconfig import get_python_inc; print(get_python_inc())") \
                       PYTHON_LIBRARY=$(python -c "import distutils.sysconfig as sysconfig; print(sysconfig.get_config_var('LIBDIR'))")"


jobs:
  build_wheels:
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        # os: [ubuntu-18.04, windows-latest, macos-latest]
        os: [ubuntu-18.04]

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
      - uses: actions/setup-python@v2
        name: Install Python
        with:
          python-version: '3.7'

      - name: Install cibuildwheel
        run: |
          python -m pip install cibuildwheel==1.5.1

      - name: Build wheels
        run: |
          python -m cibuildwheel --output-dir wheelhouse swmm-toolkit

      - uses: actions/upload-artifact@v2
        with:
          path: ./wheelhouse/*.whl
