name: Build Wheels

on: [push, pull_request]

env: 
  CIBW_SKIP: "cp27-* cp34-* cp35-* cp36-* *-win32 *_i686 *_ppc64le *_s390x"
  CIBW_BEFORE_BUILD_LINUX: pip install six scikit-build cmake && yum install -y swig


jobs:
  build_wheels:
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
        fail-fast: false
        matrix:
          os: [windows-2016, macos-10.15]
          py: [3.6, 3.7, 3.8]

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
        with:
          submodules: true

      - name: Install Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.py }}

      - name: Install build requirements
        if: ${{ contains(matrix.os, 'windows') }}
        run: choco install swig

      - if: ${{ contains(matrix.os, 'macos') }}
        run: brew install libomp swig

      - name: Build wheel
        run: pip wheel --wheel-dir=./dist ./swmm-toolkit

      - name: Test wheel
        run: |
          pip install pytest numpy
          pip install --no-index --find-links=./dist swmm-toolkit
          pytest

      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          path: ./dist/swmm_toolkit*.whl


  build_wheels_linux:
    name: Build wheels on linux
    runs-on: ubuntu-18.01

    steps:
       - name: Checkout repo
         uses: actions/checkout@v2
         with:
           submodules: true

       - name: Install Python
         uses: actions/setup-python@v2
         with:
           python-version: '3.7'

       - name: Install cibuildwheel
         run: python -m pip install cibuildwheel==1.5.1

       - name: Build wheels
         run: python -m cibuildwheel --output-dir wheelhouse swmm-toolkit

       - uses: actions/upload-artifact@v2
         with:
           path: ./wheelhouse/*.whl
