name: Build

on: [push, pull_request]

env:
    CIBW_SKIP: "cp27-* cp34-* cp35-* *-win32 *_i686 *_ppc64le *_s390x"
    CIBW_BEFORE_BUILD: pip install six scikit-build
    CIBW_TEST_COMMAND: pytest {project}\\tests
    CIBW_TEST_REQUIRES: pytest numpy

jobs:
  build_wheels:
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-18.04, windows-latest, macos-latest]

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-python@v2
        name: Install Python
        with:
          python-version: '3.7'

      - name: Install swig on macOS
        if: runner.os == 'macOS'
        run: |
          brew install swig
      - name: Install swig on Linux
        if: runner.os == 'Linux'
        run: |
          apt install swig
      - name: Install swig on Windows
        if: runner.os == 'Windows'
        run: |
          choco install swig

      - name: Install cibuildwheel
        run: |
          python -m pip install cibuildwheel==1.5.1

      # - name: Install Visual C++ for Python 2.7
      #   if: runner.os == 'Windows'
      #   run: |
      #     choco install vcpython27 -f -y

      - name: Build wheels
        run: |
          python -m cibuildwheel --output-dir wheelhouse swmm-toolkit

      - uses: actions/upload-artifact@v2
        with:
          path: ./wheelhouse/*.whl
