name: Build

on: [push, pull_request]

env:
    CIBW_SKIP: "cp27-* cp34-* cp35-* cp36-* *-win32 *_i686 *_ppc64le *_s390x"
    CIBW_BEFORE_BUILD: pip install scikit-build
    CIBW_BEFORE_BUILD_LINUX: yum install -y swig && pip install cmake scikit-build

jobs:
  build_wheels:
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
        fail-fast: false
        matrix:
          os: [ubuntu-latest]

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
        with:
          submodules: true

      - name: Install requirements
        if: ${{ contains(matrix.os, 'windows') }}
        run: choco install swig

      - if: ${{ contains(matrix.os, 'macos') }}
        run: brew install libomp swig

      - name: Install Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.7'

      - name: Install cibuildwheel
        run: |
          python -m pip install cibuildwheel==1.6.0

      - name: Build wheels
        run: python -m cibuildwheel --output-dir wheelhouse swmm-toolkit

      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          path: ./wheelhouse/*.whl
